### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'masked_lm_labels'

### ISSUE THREAD

**Issue by HelloJoyce** [heyunh2015/diseaseBERT#1]
![image](https://user-images.githubusercontent.com/21998527/117573313-c1d95580-b109-11eb-85a7-0d0ab3cee062.png)
![image](https://user-images.githubusercontent.com/21998527/117573342-e6cdc880-b109-11eb-83ed-621bfe1a967b.png)

**Comment by HelloJoyce** [comment]
transformer版本问题，好像高版本把masked_lm_labels删了

**Comment by heyunh2015** [comment]
嗯嗯，是的，用2.5.1应该可以
